ren bodybottom.html nov_bodybottom.html
ren bodyhead.html nov_bodyhead.html
ren ihead.html nov_ihead.html
ren index.html nov_index.html
ren login.html nov_login.html
ren monasteries.html nov_monasteries.html
ren monastery.html nov_monastery.html
ren order.html nov_order.html
ren orders.html nov_orders.html
ren point.html nov_point.html
ren points.html nov_points.html
ren product.html nov_product.html
ren products.html nov_products.html
ren saint.html nov_saint.html
ren saints.html nov_saints.html
ren tour.html nov_tour.html
ren tourlist.html nov_tourlist.html
ren user.html nov_user.html
ren users.html nov_users.html
