/**
 * Created by леново on 29.06.2017.s
 */

export const NOV_SENDORDER='NOV_SENDORDER';
export const NOV_ORDERSUCCESS='NOV_ORDERSUCCESS';
export const NOV_ORDERERR='NOV_ORDERERR';
export const WIN_LOADING='WIN_LOADING';
export const ADM_GETORDERS='ADM_GETORDERS';
export const ADM_GETTOURORDERS='ADM_GETTOURSORDERS';
export const ADM_GETORDER='ADM_GETORDER';
export const ADM_ORDERS_LOADED='ADM_ORDERS_LOADED';
export const WIN_SHOWTOUR='WIN_SHOWTOUR';
export const WIN_SHOWTOURLOADED='WIN_SHOWTOURLOADED';
export const ADM_TOURPOINTSLOADED='ADM_TOURPOINTSLOADED';
export const ADM_DELPOINTFROMTOUR='ADM_DELPOINTFROMTOUR';
export const ADM_ADDPOINTTOTOUR='ADM_ADDPOINTTOTOUR';


export const ADM_GETTOURDATES='ADM_GETTOURDATES';
export const ADM_DELTOURDATES='ADM_DELTOURDATES';
export const ADM_DELTOURSERVICES='ADM_DELTOURSERVICES';
export const ADM_DELTOURPHOTO='ADM_DELTOURPHOTO';

export const ADM_ADDTOURDATES='ADM_ADDTOURDATES';
export const ADM_UPDATETOURDATES='ADM_UPDATETOURDATES';

export const ADM_ADDTOURSERVICES='ADM_ADDTOURSERVICES';
export const ADM_UPDATETOURSERVICES='ADM_UPDATETOURSERVICES';


export const ADM_GETTOURSERVICES='ADM_GETTOURSERVICES';
export const ADM_GETTOURPHOTO='ADM_GETTOURPHOTO';
export const ADM_GETPOINTPHOTO='ADM_GETPOINTPHOTO';


export const ADM_TOURDATESLOADED='ADM_TOURDATESLOADED';
export const ADM_TOURSERVICESLOADED='ADM_TOURSERVICESLOADED';
export const ADM_TOURPHOTOLOADED='ADM_TOURPHOTOLOADED';
export const ADM_POINTPHOTOLOADED='ADM_POINTPHOTOLOADED';

export const ADM_WIN_OPENEDITDATE='ADM_WIN_OPENEDITDATE';
export const ADM_WIN_OPENADDDATE='ADM_WIN_OPENADDDATE';
export const ADM_WIN_OPENEDITPHOTO='ADM_WIN_OPENEDITPHOTO';
export const ADM_WIN_OPENADDPHOTO='ADM_WIN_OPENADDPHOTO';
export const ADM_WIN_OPENADDPHOTO_U='ADM_WIN_OPENADDPHOTOU';

export const ADM_WIN_OPENEDITSERVICE='ADM_WIN_OPENEDITSERVICE';
export const ADM_WIN_OPENADDSERVICE='ADM_WIN_OPENADDSERVICE';

export const ADM_WIN_CLOSEDITDATE='ADM_WIN_CLOSEDITDATE';
export const ADM_WIN_CLOSEDITSERVICE='ADM_WIN_CLOSEDITSERVICE';
export const ADM_WIN_CLOSEDITPHOTO='ADM_WIN_CLOSEDITPHOTO';


export const ADM_WIN_SAVEDATE='ADM_WIN_SAVEDATE';
export const ADM_WIN_INSERTDATE='ADM_WIN_INSERTDATE';

export const ADM_EDIT_RELOADPHOTO='ADM_EDIT_RELOADPHOTO'
export const ADM_EDIT_RELOADUPHOTO='ADM_EDIT_RELOADUPHOTO'
export const ADM_EDIT_PIC='ADM_EDIT_PIC'
export const ADM_PHOTOLOADED='ADM_PHOTOLOADED'
export const ADM_UPHOTOLOADED='ADM_UPHOTOLOADED'
export const ADM_SPREADPHOTO='ADM_SPREADPHOTO'
export const ADM_SPREADED='ADM_SPREADED'
export const SAVE_PHOTO='SAVE_PHOTO'
export const SAVE_PHOTO_SUCCESS='SAVE_PHOTO_SUCCESS'
export const SAVE_PHOTO_COMMENT='SAVE_PHOTO_COMMENT'
export const SAVE_PHOTO_TOSTORE='SAVE_PHOTO_TOSTORE'
export const ADD_NEW_TOUR='ADD_NEW_TOUR'
export const TOUR_DEPUBLISH='TOUR_DEPUBLISH'
export const TOUR_PUBLISH='TOUR_PUBLISH'
export const TOUR_DELETE='TOUR_DELETE'
export const GET_TOURORGANIZATORS='GET_TOURORGANIZATORS'
export const TOURORGANIZATORS_LOADED='TOURORGANIZATORS_LOADED'
export const CHANGE_RESERVE_STATUS='CHANGE_RESERVE_STATUS';
export const RESERVE_STATUS_DELETE='RESERVE_STATUS_DELETE';
export const RESERVE_STATUS_CANCELLED='RESERVE_STATUS_CANCELLED';
export const RESERVE_STATUS_APPROVED='RESERVE_STATUS_APPROVED';
export const EDITRESERVEDATE='EDITRESERVEDATE';
export const PILIGRIM_GO='PILIGRIM_GO';
export const PILIGRIM_NGO='PILIGRIM_NGO';
export const PILIGRIM_BADGO='PILIGRIM_BADGO';
export const SAVE_ALL_PIC='SAVE_ALL_PIC';
export const GALLERYWINDOW_SHOW='GALLERYWINDOW_SHOW';
export const GALLERYWINDOW_HIDE='GALLERYWINDOW_HIDE';
export const SAVE_ALL_PIC_RECEIVED='SAVE_ALL_PIC_RECEIVED';
export const RESERVE_MODE='RESERVE_MODE';
export const VK_AUTHORIZED='VK_AUTHORIZED';
export const ADM_GET_POINT_ADDINFO='ADM_GET_POINT_ADDINFO';
export const ADM_GET_POINT_ADDINFO_LOADED='ADM_GET_POINT_ADDINFO_LOADED';
export const ADM_DEL_POINT_ADDINFO='ADM_DEL_POINT_ADDINFO';
export const ADM_EDIT_POINT_ADDINFO='ADM_EDIT_POINT_ADDINFO';
export const ADM_EDIT_POINT_ADDINFO_CLOSE='ADM_EDIT_POINT_ADDINFO_CLOSE';
export const ADM_ADD_POINT_ADDINFO='ADM_ADD_POINT_ADDINFO';
export const ADM_UPDATE_POINT_ADDINFO='ADM_UPDATE_POINT_ADDINFO';
export const ADM_SAVE_POINT_ADDINFO='ADM_SAVE_POINT_ADDINFO';

export const EDITTOUR_GETORGANIZERS='EDITTOUR_GETORGANIZERS';
export const EDITTOUR_ORGANIZERS_LOADED='EDITTOUR_ORGANIZERS_LOADED';
export const SEND_COUPON='SEND_COUPON';
export const SEND_BILL='SEND_BILL';
export const EDIT_USERDATA_WINDOW='EDIT_USERDATA_WINDOW';
export const EDIT_USERDATA_CLOSEWINDOW='EDIT_USERDATA_CLOSEWINDOW';
export const SAVE_USERDATA='SAVE_USERDATA';
export const SAVE_USERDATA_SUCESS='SAVE_USERDATA_SUCESS';


